name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default

trigger:
  branches:
    include:
      - master

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build Image (docker-hub) - EventHorizon.Game.Server.Player
  inputs: 
    command: build
    containerRegistry: docker-hub
    repository: canhorn/ehz-platform-server-player
    Dockerfile: Dockerfile
    arguments: --build-arg BUILD_VERSION=$(Build.BuildNumber)
    tags: |
      latest
      $(Build.BuildNumber)

- task: Docker@2
  displayName: Push Image (docker-hub) - EventHorizon.Game.Server.Player 
  inputs: 
    command: push
    containerRegistry: docker-hub
    repository: canhorn/ehz-platform-server-player
    Dockerfile: Dockerfile
    tags: |
      latest
      $(Build.BuildNumber)
